/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const ProductCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'emoji' : IDL.Text,
});
export const ProductDeal = IDL.Record({
  'id' : IDL.Nat,
  'originalPrice' : IDL.Nat,
  'name' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'category' : IDL.Nat,
  'discountedPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addItemToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCartContents' : IDL.Func([], [Cart], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
  'getFeaturedDeals' : IDL.Func([], [IDL.Vec(ProductDeal)], ['query']),
  'getItemCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTotalItemCount' : IDL.Func([], [IDL.Nat], ['query']),
  'removeItemFromCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const ProductCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const ProductDeal = IDL.Record({
    'id' : IDL.Nat,
    'originalPrice' : IDL.Nat,
    'name' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'category' : IDL.Nat,
    'discountedPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'addItemToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCartContents' : IDL.Func([], [Cart], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
    'getFeaturedDeals' : IDL.Func([], [IDL.Vec(ProductDeal)], ['query']),
    'getItemCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTotalItemCount' : IDL.Func([], [IDL.Nat], ['query']),
    'removeItemFromCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };