/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<CartItem> }
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface ProductCategory {
  'id' : bigint,
  'name' : string,
  'emoji' : string,
}
export interface ProductDeal {
  'id' : bigint,
  'originalPrice' : bigint,
  'name' : string,
  'discountPercent' : bigint,
  'category' : bigint,
  'discountedPrice' : bigint,
}
export interface _SERVICE {
  'addItemToCart' : ActorMethod<[bigint, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getCartContents' : ActorMethod<[], Cart>,
  'getCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getFeaturedDeals' : ActorMethod<[], Array<ProductDeal>>,
  'getItemCount' : ActorMethod<[bigint], bigint>,
  'getTotalItemCount' : ActorMethod<[], bigint>,
  'removeItemFromCart' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];